language: csharp
dist: trusty
sudo: required
mono:
  - latest
dotnet: 1.0.4
script:
  - cd EasyConfig.UnitTests
  - dotnet restore
  - dotnet test
  - cd ../EasyConfig.Net.Core
  - dotnet restore
  - dotnet build -f netstandard1.6 -c Release
  # - xbuild ./EasyConfig.Net.Core.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.6
  - dotnet pack --no-build -o . /p:Version=1.0.$TRAVIS_BUILD_NUMBER
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH"]; then travis_terminate $TRAVIS_TEST_RESULT; fi;
  - dotnet nuget push EasyConfig.Net.Core.*.nupkg -k $NugetApiKey -s https://www.nuget.org/
