language: csharp
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
script:
  - cd EasyConfig.UnitTests
  - dotnet restore
  - dotnet test
  - cd ../EasyConfig.Net.Core
  - dotnet restore
  - dotnet build -f netstandard1.6 -c Release
  - xbuild ./EasyConfig.Net.Core.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.6.2 /toolsversion:12.0
  - dotnet pack --no-build -o . /p:Version=1.0.$TRAVIS_BUILD_NUMBER
  - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH"]; then travis_terminate 0; fi;
  - dotnet nuget push EasyConfig.Net.Core.*.nupkg -k $NugetApiKey -s https://www.nuget.org/
